version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/VosmoslaGod/Matchbot/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  start-bot:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # node ./index.js kaboom.pw 25565

workflows:
  my-custom-workflow:
    jobs:
      - start-bot